# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c137f9b016e1bc4f6684975365249ebe293297bf5dcf88706d6be52a06fe46b07dab4d2f79bb8509501d9af403a17b566d7fcbad0dd33a82388900ae0c36978

test:
  secret_key_base: 7abc17e1177042124f3cfa159d78264ffc49c8313ad4f2b2bcec2fe0324987b0f6f2505777a0939bfd7d82f32b257b30d167b848407e60a49e81bae6714c57de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
